{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9f7e554e-32ae-4582-a7d8-9d83e7f38f2d",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-07-22 14:38:40.055 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-22 14:38:40.056 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-22 14:38:40.056 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-22 14:38:40.061 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-22 14:38:40.324 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\Manjot Singh\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-07-22 14:38:40.324 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-22 14:38:40.325 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "ename": "NameError",
     "evalue": "name 'file_path' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mNameError\u001b[39m                                 Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[1]\u001b[39m\u001b[32m, line 20\u001b[39m\n\u001b[32m     17\u001b[39m \u001b[38;5;28mtype\u001b[39m = \u001b[33m\"\u001b[39m\u001b[33mfixed\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m     19\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mtype\u001b[39m == \u001b[33m\"\u001b[39m\u001b[33mfixed\u001b[39m\u001b[33m\"\u001b[39m:\n\u001b[32m---> \u001b[39m\u001b[32m20\u001b[39m     df = pd.read_excel(\u001b[43mfile_path\u001b[49m, sheet_name=\u001b[33m\"\u001b[39m\u001b[33mArea & Efficiency\u001b[39m\u001b[33m\"\u001b[39m, header=[\u001b[32m1\u001b[39m])\n\u001b[32m     21\u001b[39m     df.columns = df.columns.str.strip()\n\u001b[32m     22\u001b[39m     null_indices = df[df[\u001b[33m'\u001b[39m\u001b[33mModule Type\u001b[39m\u001b[33m'\u001b[39m].isna()].index\n",
      "\u001b[31mNameError\u001b[39m: name 'file_path' is not defined"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from scipy.optimize import differential_evolution\n",
    "from sklearn.metrics import mean_absolute_percentage_error\n",
    "import streamlit as st\n",
    "\n",
    "uploaded_file = st.file_uploader(\n",
    "    \"Upload Excel File\",\n",
    "    type=[\"xlsx\"]\n",
    ")\n",
    "\n",
    "if uploaded_file is not None:\n",
    "    file_path = uploaded_file\n",
    "\n",
    "#Variables\n",
    "type = \"fixed\"\n",
    "\n",
    "if type == \"fixed\":\n",
    "    df = pd.read_excel(file_path, sheet_name=\"Area & Efficiency\", header=[1])\n",
    "    df.columns = df.columns.str.strip()\n",
    "    null_indices = df[df['Module Type'].isna()].index\n",
    "    first_null_pos = df.index.get_loc(null_indices[0])\n",
    "    df = df.iloc[:first_null_pos]\n",
    "\n",
    "    df_st = pd.read_excel(file_path, sheet_name=\"Forecast Config\", header=[8])\n",
    "    lat = float(df_st.loc[0, \"Lat\"])\n",
    "\n",
    "    df_tilt = pd.read_excel(file_path, sheet_name=\"Config Tilt Angle\", header=[7])\n",
    "    df_tilt.columns = df_tilt.columns.str.strip()\n",
    "    null_indices = df_tilt[df_tilt['Fixed'].isna()].index\n",
    "    first_null_pos = df_tilt.index.get_loc(null_indices[0])\n",
    "    df_tilt = df_tilt.iloc[:first_null_pos]\n",
    "    df_tilt = df_tilt.dropna(how='all', axis=1)\n",
    "    df_tilt = df_tilt.rename(columns={\n",
    "        'Unnamed: 2': 'Month_Num',\n",
    "        'Unnamed: 3': 'Month',\n",
    "    })\n",
    "    month_lookup = df_tilt.set_index('Month')['Fixed'].to_dict()\n",
    "\n",
    "    df_fix = pd.read_excel(file_path, sheet_name=\"Fixed\", header=[1])\n",
    "    df_fix.columns = df_fix.columns.str.strip()\n",
    "    null_indices = df_fix[df_fix['Date'].isna()].index\n",
    "    first_null_pos = df_fix.index.get_loc(null_indices[0])\n",
    "    df_fix = df_fix.iloc[:first_null_pos]\n",
    "\n",
    "    df_fix[\"Date\"] = pd.Timestamp.today()\n",
    "    first_date = pd.Timestamp.today().replace(month=1, day=1).normalize()\n",
    "\n",
    "    df_fix[\"Declination Angle ∆\"] = 23.45 * (\n",
    "        np.sin(\n",
    "            np.radians(\n",
    "                360 * (284 + (df_fix[\"Date\"] - first_date).dt.days + 1) / 365\n",
    "            )\n",
    "        )\n",
    "    )\n",
    "\n",
    "    df_fix[\"Elevation angle a\"] = (90 - lat + df_fix[\"Declination Angle ∆\"])\n",
    "    df_fix[\"Tilt Angle b\"] = df_fix[\"Date\"].dt.strftime('%B').map(month_lookup)\n",
    "    df_fix[\"a+b\"] = df_fix[\"Elevation angle a\"] + df_fix[\"Tilt Angle b\"]\n",
    "    df_fix[\"SIN(a+b)\"] = np.sin(np.radians(df_fix[\"a+b\"]))\n",
    "    df_fix[\"Sin(a)\"] = np.sin(np.radians(df_fix[\"Elevation angle a\"]))\n",
    "    df_fix[\"GHI*sin(a)\"] = df_fix[\"GHI_Forecast\"] * df_fix[\"Sin(a)\"]\n",
    "    df_fix[\"GHI*sin(a+b)\"] = df_fix[\"GHI_Forecast\"] * df_fix[\"SIN(a+b)\"]\n",
    "    df_fix[\"POA fixed\"] = df_fix[\"GHI*sin(a+b)\"] / df_fix[\"Sin(a)\"]\n",
    "\n",
    "    # Maximum possible loss\n",
    "    max_loss = df[\"Standard PV Efficiency (%)\"].min()\n",
    "\n",
    "    #peak_error = abs(actual_peak - predicted_peak) / actual_peak * 100\n",
    "\n",
    "    results = []\n",
    "\n",
    "    for loss in np.arange(0, max_loss + 0.01, 0.1):\n",
    "\n",
    "        df[\"Efficiency Losses(%)\"] = loss\n",
    "        df[\"Net Efficiency (%)\"] = df[\"Standard PV Efficiency (%)\"] - df[\"Efficiency Losses(%)\"]\n",
    "        df[\"Eff Area\"] = (df[\"Total area(m2)\"] * df[\"Net Efficiency (%)\"]) / 100\n",
    "    \n",
    "        df_fix[\"Fixed Power=I*Ƞ*A\"] = (\n",
    "            df_fix[\"POA fixed\"] * np.sum(df[\"Eff Area\"])\n",
    "        ) / 1000000\n",
    "\n",
    "        # Peak power comparison\n",
    "        actual_peak = df_fix[\"Actual\"].max()\n",
    "        predicted_peak = df_fix[\"Fixed Power=I*Ƞ*A\"].max()\n",
    "\n",
    "        peak_error = abs(actual_peak - predicted_peak)\n",
    "\n",
    "        results.append({\n",
    "            \"Efficiency Loss (%)\": loss,\n",
    "            \"Actual Peak\": actual_peak,\n",
    "            \"Predicted Peak\": predicted_peak,\n",
    "            \"Peak Error\": peak_error\n",
    "        })\n",
    "        results_df = pd.DataFrame(results)\n",
    "\n",
    "    # Get efficiency loss with least Peak Error\n",
    "    best_loss = results_df.loc[\n",
    "        results_df[\"Peak Error\"].idxmin(),\n",
    "        \"Efficiency Loss (%)\"\n",
    "    ]\n",
    "\n",
    "    # Assign best efficiency loss\n",
    "    df[\"Efficiency Losses(%)\"] = best_loss\n",
    "\n",
    "    # Recalculate dependent columns\n",
    "    df[\"Net Efficiency (%)\"] = (\n",
    "        df[\"Standard PV Efficiency (%)\"] - df[\"Efficiency Losses(%)\"]\n",
    "    )\n",
    "\n",
    "    df[\"Eff Area\"] = (\n",
    "        df[\"Total area(m2)\"] * df[\"Net Efficiency (%)\"]\n",
    "    ) / 100\n",
    "\n",
    "    # Recalculate final power using the best efficiency loss\n",
    "    df_fix[\"Fixed Power=I*Ƞ*A\"] = (\n",
    "        df_fix[\"POA fixed\"] * df[\"Eff Area\"].sum()\n",
    "    ) / 1_000_000\n",
    "\n",
    "    print(f\"Best Efficiency Loss = {best_loss:.2f}%\")\n",
    "\n",
    "    p = np.arange(0, 96)\n",
    "    plt.figure(figsize=(14,6))\n",
    "    plt.plot(p, df_fix[\"Fixed Power=I*Ƞ*A\"], color='green', label = \"Forecast\", linewidth=2)\n",
    "    plt.plot(p, df_fix[\"Actual\"], color='blue', label = \"Actual\", linewidth=2)\n",
    "    plt.xlim(0, 96)\n",
    "    plt.legend()\n",
    "    plt.grid(True)\n",
    "    st.pyplot(plt.gcf())\n",
    "elif type == \"tracking\":\n",
    "    df = pd.read_excel(file_path, sheet_name=\"Area & Efficiency\", header=[1])\n",
    "    df.columns = df.columns.str.strip()\n",
    "    null_indices = df[df['Module Type'].isna()].index\n",
    "    first_null_pos = df.index.get_loc(null_indices[0])\n",
    "    df = df.iloc[:first_null_pos]\n",
    "\n",
    "    df_st = pd.read_excel(file_path, sheet_name=\"Forecast Config\", header=[8])\n",
    "    lat = float(df_st.loc[0, \"Lat\"])\n",
    "\n",
    "    df_tilt = pd.read_excel(file_path, sheet_name=\"Config Tilt Angle\", header=[7])\n",
    "    df_tilt.columns = df_tilt.columns.str.strip()\n",
    "    null_indices = df_tilt[df_tilt['Fixed'].isna()].index\n",
    "    first_null_pos = df_tilt.index.get_loc(null_indices[0])\n",
    "    df_tilt = df_tilt.iloc[:first_null_pos]\n",
    "    df_tilt = df_tilt.dropna(how='all', axis=1)\n",
    "    df_tilt = df_tilt.rename(columns={\n",
    "        'Unnamed: 2': 'Month_Num',\n",
    "        'Unnamed: 3': 'Month',\n",
    "    })\n",
    "    #month_lookup = df_tilt.set_index('Month')['Fixed'].to_dict()\n",
    "\n",
    "    df_fix = pd.read_excel(file_path, sheet_name=\"Fixed\", header=[1])\n",
    "    df_fix.columns = df_fix.columns.str.strip()\n",
    "    df_fix[\"Actual\"] = df_fix[\"Actual\"].fillna(0)\n",
    "    null_indices = df_fix[df_fix['Date'].isna()].index\n",
    "    first_null_pos = df_fix.index.get_loc(null_indices[0])\n",
    "    df_fix = df_fix.iloc[:first_null_pos]\n",
    "\n",
    "    df_fix[\"Date\"] = pd.Timestamp.today()\n",
    "    first_date = pd.Timestamp.today().replace(month=1, day=1).normalize()\n",
    "\n",
    "    df_fix[\"Declination Angle ∆\"] = 23.45 * (\n",
    "        np.sin(\n",
    "            np.radians(\n",
    "                360 * (284 + (df_fix[\"Date\"] - first_date).dt.days + 1) / 365\n",
    "            )\n",
    "        )\n",
    "    )\n",
    "\n",
    "    df_fix[\"Elevation angle a\"] = (90 - lat + df_fix[\"Declination Angle ∆\"])\n",
    "    df_fix[\"Tilt Angle b\"] = df_fix[\"Date\"].dt.strftime('%B').map(month_lookup)\n",
    "    df_fix[\"a+b\"] = df_fix[\"Elevation angle a\"] + df_fix[\"Tilt Angle b\"]\n",
    "    df_fix[\"SIN(a+b)\"] = np.sin(np.radians(df_fix[\"a+b\"]))\n",
    "    df_fix[\"Sin(a)\"] = np.sin(np.radians(df_fix[\"Elevation angle a\"]))\n",
    "    df_fix[\"GHI*sin(a)\"] = df_fix[\"GHI_Forecast\"] * df_fix[\"Sin(a)\"]\n",
    "    df_fix[\"GHI*sin(a+b)\"] = df_fix[\"GHI_Forecast\"] * df_fix[\"SIN(a+b)\"]\n",
    "    df_fix[\"POA fixed\"] = df_fix[\"GHI*sin(a+b)\"] / df_fix[\"Sin(a)\"]\n",
    "\n",
    "    # Maximum possible loss\n",
    "    max_loss = df[\"Standard PV Efficiency (%)\"].min()\n",
    "\n",
    "    #peak_error = abs(actual_peak - predicted_peak) / actual_peak * 100\n",
    "\n",
    "    results = []\n",
    "\n",
    "    for loss in np.arange(0, max_loss + 0.01, 0.1):\n",
    "\n",
    "        df[\"Efficiency Losses(%)\"] = loss\n",
    "        df[\"Net Efficiency (%)\"] = df[\"Standard PV Efficiency (%)\"] - df[\"Efficiency Losses(%)\"]\n",
    "        df[\"Eff Area\"] = (df[\"Total area(m2)\"] * df[\"Net Efficiency (%)\"]) / 100\n",
    "    \n",
    "        df_fix[\"Fixed Power=I*Ƞ*A\"] = (\n",
    "            df_fix[\"POA fixed\"] * np.sum(df[\"Eff Area\"])\n",
    "        ) / 1000000\n",
    "\n",
    "        # Peak power comparison\n",
    "        actual_peak = df_fix[\"Actual\"].max()\n",
    "        predicted_peak = df_fix[\"Fixed Power=I*Ƞ*A\"].max()\n",
    "\n",
    "        peak_error = abs(actual_peak - predicted_peak)\n",
    "\n",
    "        results.append({\n",
    "            \"Efficiency Loss (%)\": loss,\n",
    "            \"Actual Peak\": actual_peak,\n",
    "            \"Predicted Peak\": predicted_peak,\n",
    "            \"Peak Error\": peak_error\n",
    "        })\n",
    "\n",
    "    results_df = pd.DataFrame(results)\n",
    "\n",
    "    # Get efficiency loss with least Peak Error\n",
    "    best_loss = results_df.loc[\n",
    "        results_df[\"Peak Error\"].idxmin(),\n",
    "        \"Efficiency Loss (%)\"\n",
    "    ]\n",
    "\n",
    "    # Assign best efficiency loss\n",
    "    df[\"Efficiency Losses(%)\"] = best_loss\n",
    "\n",
    "    # Recalculate dependent columns\n",
    "    df[\"Net Efficiency (%)\"] = (\n",
    "        df[\"Standard PV Efficiency (%)\"] - df[\"Efficiency Losses(%)\"]\n",
    "    )\n",
    "\n",
    "    df[\"Eff Area\"] = (\n",
    "        df[\"Total area(m2)\"] * df[\"Net Efficiency (%)\"]\n",
    "    ) / 100\n",
    "\n",
    "    # Recalculate final power using the best efficiency loss\n",
    "    df_fix[\"Fixed Power=I*Ƞ*A\"] = (\n",
    "        df_fix[\"POA fixed\"] * df[\"Eff Area\"].sum()\n",
    "    ) / 1_000_000\n",
    "    # ------------------ Read Data ------------------\n",
    "\n",
    "    df_bcal = pd.read_excel(file_path, sheet_name=\"Backend Cal\")\n",
    "    df_trac = pd.read_excel(file_path, sheet_name=\"Tracking\", header=[1])\n",
    "\n",
    "    # ------------------ Objective Function ------------------\n",
    "\n",
    "    def objective(x):\n",
    "\n",
    "        DHI = int(round(x[0]))\n",
    "        GHI_Starting_Block = int(round(x[1]))\n",
    "        GHI_Ending_Block = int(round(x[2]))\n",
    "        GHI_Max_Block = int(round(x[3]))\n",
    "        Tracking_angle_lim_E = int(round(x[4]))\n",
    "        Tracking_angle_lim_W = int(round(x[5]))\n",
    "\n",
    "        # Invalid combinations\n",
    "        if (\n",
    "            GHI_Starting_Block >= GHI_Max_Block\n",
    "            or GHI_Max_Block >= GHI_Ending_Block\n",
    "        ):\n",
    "            return 1e9\n",
    "\n",
    "        m1 = 90 / (GHI_Starting_Block - 1 - GHI_Max_Block)\n",
    "        m2 = 90 / (GHI_Ending_Block + 1 - GHI_Max_Block)\n",
    "\n",
    "        temp = df_bcal.copy()\n",
    "\n",
    "        temp[\"DHI\"] = df_fix[\"GHI_Forecast\"] * DHI / 100\n",
    "        temp[\"GHI - DHI\"] = df_fix[\"GHI_Forecast\"] - temp[\"DHI\"]\n",
    "\n",
    "        temp[\"Zenith angle ( θ )\"] = np.where(\n",
    "            temp[\"Block No.\"] <= GHI_Max_Block,\n",
    "            np.minimum(89, m1 * (temp[\"Block No.\"] - GHI_Max_Block)),\n",
    "            np.minimum(89, m2 * (temp[\"Block No.\"] - GHI_Max_Block))\n",
    "        )\n",
    "\n",
    "        temp[\"Panel Angle (α)\"] = np.where(\n",
    "            temp[\"Block No.\"] < GHI_Max_Block,\n",
    "            np.where(\n",
    "                temp[\"Zenith angle ( θ )\"] < abs(Tracking_angle_lim_E),\n",
    "                temp[\"Zenith angle ( θ )\"],\n",
    "                abs(Tracking_angle_lim_E)\n",
    "            ),\n",
    "            np.where(\n",
    "                (temp[\"Block No.\"] > GHI_Max_Block) &\n",
    "                (temp[\"Zenith angle ( θ )\"] > Tracking_angle_lim_W),\n",
    "                Tracking_angle_lim_W,\n",
    "                temp[\"Zenith angle ( θ )\"]\n",
    "            )\n",
    "        )\n",
    "\n",
    "        temp[\"θ - α\"] = temp[\"Zenith angle ( θ )\"] - temp[\"Panel Angle (α)\"]\n",
    "\n",
    "        temp[\"Cos(θ)\"] = np.cos(np.radians(temp[\"Zenith angle ( θ )\"]))\n",
    "        temp[\"Cos(α)\"] = np.cos(np.radians(temp[\"Panel Angle (α)\"]))\n",
    "        temp[\"Cos(θ - α)\"] = np.cos(np.radians(temp[\"θ - α\"]))\n",
    "\n",
    "        temp[\"DNI\"] = temp[\"GHI - DHI\"] / temp[\"Cos(α)\"]\n",
    "\n",
    "        prediction = (temp[\"DNI\"] * df[\"Eff Area\"].sum()) / 1_000_000\n",
    "\n",
    "        mask = df_fix[\"Actual\"] != 0\n",
    "\n",
    "        from sklearn.metrics import mean_squared_error\n",
    "\n",
    "        actual = df_fix[\"Actual\"].values\n",
    "        prediction = prediction.values\n",
    "\n",
    "        # Consider only daylight blocks\n",
    "        mask = df_fix[\"GHI_Forecast\"].values > 50\n",
    "\n",
    "        actual = actual[mask]\n",
    "        prediction = prediction[mask]\n",
    "\n",
    "        # Higher weights near peak generation\n",
    "        weights = actual / actual.max()\n",
    "\n",
    "        # Weighted RMSE\n",
    "        block_error = np.mean(np.abs(actual - prediction)) / actual.max()\n",
    "\n",
    "        # Peak error\n",
    "        peak_error = abs(actual.max() - prediction.max()) / actual.max()\n",
    "\n",
    "        # Daily energy error\n",
    "        energy_error = abs(actual.sum() - prediction.sum()) / actual.sum()\n",
    "\n",
    "        score = (\n",
    "            0.80 * block_error +\n",
    "            0.10 * peak_error +\n",
    "            0.10 * energy_error\n",
    "        )\n",
    "\n",
    "        return score\n",
    "\n",
    "\n",
    "    # ------------------ Parameter Bounds ------------------\n",
    "\n",
    "    bounds = [\n",
    "        (0, 10),      # DHI (%)\n",
    "        (10, 30),     # GHI Starting Block\n",
    "        (65, 80),     # GHI Ending Block\n",
    "        (47, 53),     # GHI Max Block\n",
    "        (10, 70),     # Tracking East Limit\n",
    "        (10, 70)      # Tracking West Limit\n",
    "    ]\n",
    "\n",
    "    # ------------------ Optimization ------------------\n",
    "\n",
    "    result = differential_evolution(\n",
    "        objective,\n",
    "        bounds=bounds,\n",
    "        strategy=\"best1bin\",\n",
    "        maxiter=40,\n",
    "        popsize=15,\n",
    "        tol=0.001,\n",
    "        mutation=(0.5, 1),\n",
    "        recombination=0.7,\n",
    "        seed=42,\n",
    "        polish=True,\n",
    "        workers=1        # Use -1 on Linux/macOS if multiprocessing works\n",
    "    )\n",
    "\n",
    "    # ------------------ Best Parameters ------------------\n",
    "\n",
    "    best = np.round(result.x).astype(int)\n",
    "\n",
    "    DHI = best[0]\n",
    "    GHI_Starting_Block = best[1]\n",
    "    GHI_Ending_Block = best[2]\n",
    "    GHI_Max_Block = best[3]\n",
    "    Tracking_angle_lim_E = best[4]\n",
    "    Tracking_angle_lim_W = best[5]\n",
    "\n",
    "    print(\"Error Score:\", result.fun)\n",
    "    print(\"DHI:\", DHI)\n",
    "    print(\"GHI Starting Block:\", GHI_Starting_Block)\n",
    "    print(\"GHI Ending Block:\", GHI_Ending_Block)\n",
    "    print(\"GHI Max Block:\", GHI_Max_Block)\n",
    "    print(\"Tracking East Limit:\", Tracking_angle_lim_E)\n",
    "    print(\"Tracking West Limit:\", Tracking_angle_lim_W)\n",
    "    print(\"Efficiency Loss:\", best_loss)\n",
    "\n",
    "    # ------------------ Final Calculation Using Best Parameters ------------------\n",
    "\n",
    "    m1 = 90 / (GHI_Starting_Block - 1 - GHI_Max_Block)\n",
    "    m2 = 90 / (GHI_Ending_Block + 1 - GHI_Max_Block)\n",
    "\n",
    "    df_bcal[\"DHI\"] = df_fix[\"GHI_Forecast\"] * DHI / 100\n",
    "    df_bcal[\"GHI - DHI\"] = df_fix[\"GHI_Forecast\"] - df_bcal[\"DHI\"]\n",
    "\n",
    "    df_bcal[\"Zenith angle ( θ )\"] = np.where(\n",
    "        df_bcal[\"Block No.\"] <= GHI_Max_Block,\n",
    "        np.minimum(89, m1 * (df_bcal[\"Block No.\"] - GHI_Max_Block)),\n",
    "        np.minimum(89, m2 * (df_bcal[\"Block No.\"] - GHI_Max_Block))\n",
    "    )\n",
    "\n",
    "    df_bcal[\"Panel Angle (α)\"] = np.where(\n",
    "        df_bcal[\"Block No.\"] < GHI_Max_Block,\n",
    "        np.where(\n",
    "            df_bcal[\"Zenith angle ( θ )\"] < abs(Tracking_angle_lim_E),\n",
    "            df_bcal[\"Zenith angle ( θ )\"],\n",
    "            abs(Tracking_angle_lim_E)\n",
    "        ),\n",
    "        np.where(\n",
    "            (df_bcal[\"Block No.\"] > GHI_Max_Block) &\n",
    "            (df_bcal[\"Zenith angle ( θ )\"] > Tracking_angle_lim_W),\n",
    "            Tracking_angle_lim_W,\n",
    "            df_bcal[\"Zenith angle ( θ )\"]\n",
    "        )\n",
    "    )\n",
    "\n",
    "    df_bcal[\"θ - α\"] = df_bcal[\"Zenith angle ( θ )\"] - df_bcal[\"Panel Angle (α)\"]\n",
    "    df_bcal[\"Cos(θ)\"] = np.cos(np.radians(df_bcal[\"Zenith angle ( θ )\"]))\n",
    "    df_bcal[\"Cos(α)\"] = np.cos(np.radians(df_bcal[\"Panel Angle (α)\"]))\n",
    "    df_bcal[\"Cos(θ - α)\"] = np.cos(np.radians(df_bcal[\"θ - α\"]))\n",
    "    df_bcal[\"DNI\"] = df_bcal[\"GHI - DHI\"] / df_bcal[\"Cos(α)\"]\n",
    "\n",
    "    df_trac[\"Fixed Power=I*Ƞ*A\"] = (\n",
    "        df_bcal[\"DNI\"] * df[\"Eff Area\"].sum()\n",
    "    ) / 1000000\n",
    "\n",
    "    p = np.arange(0, 96)\n",
    "    plt.figure(figsize=(14,6))\n",
    "    #plt.plot(p, df_bcal[\"Panel Angle (α)\"], color='green', linewidth=2)\n",
    "    plt.plot(p, df_trac[\"Fixed Power=I*Ƞ*A\"], label=\"Forecast\", color='Blue', linewidth=2)\n",
    "    plt.plot(p, df_fix[\"Actual\"], label=\"Actual\", color='Red', linewidth=2)\n",
    "    plt.xlim(0, 96)\n",
    "    plt.legend()\n",
    "    plt.grid(True)\n",
    "    st.pyplot(plt.gcf())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f6138056-be25-43f5-aecb-46f52ee673f3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
